<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      
        DB::table('tblcountries')->delete();

        $countries = array(
            array('fldid' => '1','fldname' => 'AFGHANISTAN'),
            array('fldid' => '2','fldname' => 'ALBANIA'),
            array('fldid' => '3','fldname' => 'ALGERIA'),
            array('fldid' => '4','fldname' => 'AMERICAN SAMOA'),
            array('fldid' => '5','fldname' => 'ANDORRA'),
            array('fldid' => '6','fldname' => 'ANGOLA'),
            array('fldid' => '7','fldname' => 'ANGUILLA'),
            array('fldid' => '8','fldname' => 'ANTARCTICA'),
            array('fldid' => '9','fldname' => 'ANTIGUA AND BARBUDA'),
            array('fldid' => '10','fldname' => 'ARGENTINA'),
            array('fldid' => '11','fldname' => 'ARMENIA'),
            array('fldid' => '12','fldname' => 'ARUBA'),
            array('fldid' => '13','fldname' => 'AUSTRALIA'),
            array('fldid' => '14','fldname' => 'AUSTRIA'),
            array('fldid' => '15','fldname' => 'AZERBAIJAN'),
            array('fldid' => '16','fldname' => 'BAHAMAS'),
            array('fldid' => '17','fldname' => 'BAHRAIN'),
            array('fldid' => '18','fldname' => 'BANGLADESH'),
            array('fldid' => '19','fldname' => 'BARBADOS'),
            array('fldid' => '20','fldname' => 'BELARUS'),
            array('fldid' => '21','fldname' => 'BELGIUM'),
            array('fldid' => '22','fldname' => 'BELIZE'),
            array('fldid' => '23','fldname' => 'BENIN'),
            array('fldid' => '24','fldname' => 'BERMUDA'),
            array('fldid' => '25','fldname' => 'BHUTAN'),
            array('fldid' => '26','fldname' => 'BOLIVIA'),
            array('fldid' => '27','fldname' => 'BOSNIA AND HERZEGOVINA'),
            array('fldid' => '28','fldname' => 'BOTSWANA'),
            array('fldid' => '29','fldname' => 'BOUVET ISLAND'),
            array('fldid' => '30','fldname' => 'BRAZIL'),
            array('fldid' => '31','fldname' => 'BRITISH INDIAN OCEAN TERRITORY'),
            array('fldid' => '32','fldname' => 'BRUNEI DARUSSALAM'),
            array('fldid' => '33','fldname' => 'BULGARIA'),
            array('fldid' => '34','fldname' => 'BURKINA FASO'),
            array('fldid' => '35','fldname' => 'BURUNDI'),
            array('fldid' => '36','fldname' => 'CAMBODIA'),
            array('fldid' => '37','fldname' => 'CAMEROON'),
            array('fldid' => '38','fldname' => 'CANADA'),
            array('fldid' => '39','fldname' => 'CAPE VERDE'),
            array('fldid' => '40','fldname' => 'CAYMAN ISLANDS'),
            array('fldid' => '41','fldname' => 'CENTRAL AFRICAN REPUBLIC'),
            array('fldid' => '42','fldname' => 'CHAD'),
            array('fldid' => '43','fldname' => 'CHILE'),
            array('fldid' => '44','fldname' => 'CHINA'),
            array('fldid' => '45','fldname' => 'CHRISTMAS ISLAND'),
            array('fldid' => '46','fldname' => 'COCOS (KEELING) ISLANDS'),
            array('fldid' => '47','fldname' => 'COLOMBIA'),
            array('fldid' => '48','fldname' => 'COMOROS'),
            array('fldid' => '49','fldname' => 'CONGO'),
            array('fldid' => '50','fldname' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE'),
            array('fldid' => '51','fldname' => 'COOK ISLANDS'),
            array('fldid' => '52','fldname' => 'COSTA RICA'),
            array('fldid' => '53','fldname' => 'COTE D\'IVOIRE'),
            array('fldid' => '54','fldname' => 'CROATIA'),
            array('fldid' => '55','fldname' => 'CUBA'),
            array('fldid' => '57','fldname' => 'CZECH REPUBLIC'),
            array('fldid' => '58','fldname' => 'DENMARK'),
            array('fldid' => '59','fldname' => 'DJIBOUTI'),
            array('fldid' => '60','fldname' => 'DOMINICA'),
            array('fldid' => '61','fldname' => 'DOMINICAN REPUBLIC'),
            array('fldid' => '62','fldname' => 'ECUADOR'),
            array('fldid' => '63','fldname' => 'EGYPT'),
            array('fldid' => '64','fldname' => 'EL SALVADOR'),
            array('fldid' => '65','fldname' => 'EQUATORIAL GUINEA'),
            array('fldid' => '66','fldname' => 'ERITREA'),
            array('fldid' => '67','fldname' => 'ESTONIA'),
            array('fldid' => '68','fldname' => 'ETHIOPIA'),
            array('fldid' => '69','fldname' => 'FALKLAND ISLANDS (MALVINAS)'),
            array('fldid' => '70','fldname' => 'FAROE ISLANDS'),
            array('fldid' => '71','fldname' => 'FIJI'),
            array('fldid' => '72','fldname' => 'FINLAND'),
            array('fldid' => '73','fldname' => 'FRANCE'),
            array('fldid' => '74','fldname' => 'FRENCH GUIANA'),
            array('fldid' => '75','fldname' => 'FRENCH POLYNESIA'),
            array('fldid' => '76','fldname' => 'FRENCH SOUTHERN TERRITORIES'),
            array('fldid' => '77','fldname' => 'GABON'),
            array('fldid' => '78','fldname' => 'GAMBIA'),
            array('fldid' => '79','fldname' => 'GEORGIA'),
            array('fldid' => '80','fldname' => 'GERMANY'),
            array('fldid' => '81','fldname' => 'GHANA'),
            array('fldid' => '82','fldname' => 'GIBRALTAR'),
            array('fldid' => '83','fldname' => 'GREECE'),
            array('fldid' => '84','fldname' => 'GREENLAND'),
            array('fldid' => '85','fldname' => 'GRENADA'),
            array('fldid' => '86','fldname' => 'GUADELOUPE'),
            array('fldid' => '87','fldname' => 'GUAM'),
            array('fldid' => '88','fldname' => 'GUATEMALA'),
            array('fldid' => '89','fldname' => 'GUINEA'),
            array('fldid' => '90','fldname' => 'GUINEA-BISSAU'),
            array('fldid' => '91','fldname' => 'GUYANA'),
            array('fldid' => '92','fldname' => 'HAITI'),
            array('fldid' => '93','fldname' => 'HEARD ISLAND AND MCDONALD ISLANDS'),
            array('fldid' => '94','fldname' => 'HOLY SEE (VATICAN CITY STATE)'),
            array('fldid' => '95','fldname' => 'HONDURAS'),
            array('fldid' => '96','fldname' => 'HONG KONG'),
            array('fldid' => '97','fldname' => 'HUNGARY'),
            array('fldid' => '98','fldname' => 'ICELAND'),
            array('fldid' => '99','fldname' => 'INDIA'),
            array('fldid' => '100','fldname' => 'INDONESIA'),
            array('fldid' => '101','fldname' => 'IRAN, ISLAMIC REPUBLIC OF'),
            array('fldid' => '102','fldname' => 'IRAQ'),
            array('fldid' => '103','fldname' => 'IRELAND'),
            array('fldid' => '104','fldname' => 'ISRAEL'),
            array('fldid' => '105','fldname' => 'ITALY'),
            array('fldid' => '106','fldname' => 'JAMAICA'),
            array('fldid' => '107','fldname' => 'JAPAN'),
            array('fldid' => '108','fldname' => 'JORDAN'),
            array('fldid' => '109','fldname' => 'KAZAKHSTAN'),
            array('fldid' => '110','fldname' => 'KENYA'),
            array('fldid' => '111','fldname' => 'KIRIBATI'),
            array('fldid' => '112','fldname' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF'),
            array('fldid' => '113','fldname' => 'KOREA, REPUBLIC OF'),
            array('fldid' => '114','fldname' => 'KUWAIT'),
            array('fldid' => '115','fldname' => 'KYRGYZSTAN'),
            array('fldid' => '116','fldname' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC'),
            array('fldid' => '117','fldname' => 'LATVIA'),
            array('fldid' => '118','fldname' => 'LEBANON'),
            array('fldid' => '119','fldname' => 'LESOTHO'),
            array('fldid' => '120','fldname' => 'LIBERIA'),
            array('fldid' => '121','fldname' => 'LIBYAN ARAB JAMAHIRIYA'),
            array('fldid' => '122','fldname' => 'LIECHTENSTEIN'),
            array('fldid' => '123','fldname' => 'LITHUANIA'),
            array('fldid' => '124','fldname' => 'LUXEMBOURG'),
            array('fldid' => '125','fldname' => 'MACAO'),
            array('fldid' => '126','fldname' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF'),
            array('fldid' => '127','fldname' => 'MADAGASCAR'),
            array('fldid' => '128','fldname' => 'MALAWI'),
            array('fldid' => '129','fldname' => 'MALAYSIA'),
            array('fldid' => '130','fldname' => 'MALDIVES'),
            array('fldid' => '131','fldname' => 'MALI'),
            array('fldid' => '132','fldname' => 'MALTA'),
            array('fldid' => '133','fldname' => 'MARSHALL ISLANDS'),
            array('fldid' => '134','fldname' => 'MARTINIQUE'),
            array('fldid' => '135','fldname' => 'MAURITANIA'),
            array('fldid' => '136','fldname' => 'MAURITIUS'),
            array('fldid' => '137','fldname' => 'MAYOTTE'),
            array('fldid' => '138','fldname' => 'MEXICO'),
            array('fldid' => '139','fldname' => 'MICRONESIA, FEDERATED STATES OF'),
            array('fldid' => '140','fldname' => 'MOLDOVA, REPUBLIC OF'),
            array('fldid' => '141','fldname' => 'MONACO'),
            array('fldid' => '142','fldname' => 'MONGOLIA'),
            array('fldid' => '143','fldname' => 'MONTSERRAT'),
            array('fldid' => '144','fldname' => 'MOROCCO'),
            array('fldid' => '145','fldname' => 'MOZAMBIQUE'),
            array('fldid' => '146','fldname' => 'MYANMAR'),
            array('fldid' => '147','fldname' => 'NAMIBIA'),
            array('fldid' => '148','fldname' => 'NAURU'),
            array('fldid' => '149','fldname' => 'NEPAL'),
            array('fldid' => '150','fldname' => 'NETHERLANDS'),
            array('fldid' => '151','fldname' => 'NETHERLANDS ANTILLES'),
            array('fldid' => '152','fldname' => 'NEW CALEDONIA'),
            array('fldid' => '153','fldname' => 'NEW ZEALAND'),
            array('fldid' => '154','fldname' => 'NICARAGUA'),
            array('fldid' => '155','fldname' => 'NIGER'),
            array('fldid' => '156','fldname' => 'NIGERIA'),
            array('fldid' => '157','fldname' => 'NIUE'),
            array('fldid' => '158','fldname' => 'NORFOLK ISLAND'),
            array('fldid' => '159','fldname' => 'NORTHERN MARIANA ISLANDS'),
            array('fldid' => '160','fldname' => 'NORWAY'),
            array('fldid' => '161','fldname' => 'OMAN'),
            array('fldid' => '162','fldname' => 'PAKISTAN'),
            array('fldid' => '163','fldname' => 'PALAU'),
            array('fldid' => '164','fldname' => 'PALESTINIAN TERRITORY, OCCUPIED'),
            array('fldid' => '165','fldname' => 'PANAMA'),
            array('fldid' => '166','fldname' => 'PAPUA NEW GUINEA'),
            array('fldid' => '167','fldname' => 'PARAGUAY'),
            array('fldid' => '168','fldname' => 'PERU'),
            array('fldid' => '170','fldname' => 'PITCAIRN'),
            array('fldid' => '171','fldname' => 'POLAND'),
            array('fldid' => '172','fldname' => 'PORTUGAL'),
            array('fldid' => '173','fldname' => 'PUERTO RICO'),
            array('fldid' => '174','fldname' => 'QATAR'),
            array('fldid' => '175','fldname' => 'REUNION'),
            array('fldid' => '176','fldname' => 'ROMANIA'),
            array('fldid' => '177','fldname' => 'RUSSIAN FEDERATION'),
            array('fldid' => '178','fldname' => 'RWANDA'),
            array('fldid' => '179','fldname' => 'SAINT HELENA'),
            array('fldid' => '180','fldname' => 'SAINT KITTS AND NEVIS'),
            array('fldid' => '181','fldname' => 'SAINT LUCIA'),
            array('fldid' => '182','fldname' => 'SAINT PIERRE AND MIQUELON'),
            array('fldid' => '183','fldname' => 'SAINT VINCENT AND THE GRENADINES'),
            array('fldid' => '184','fldname' => 'SAMOA'),
            array('fldid' => '185','fldname' => 'SAN MARINO'),
            array('fldid' => '186','fldname' => 'SAO TOME AND PRINCIPE'),
            array('fldid' => '187','fldname' => 'SAUDI ARABIA'),
            array('fldid' => '188','fldname' => 'SENEGAL'),
            array('fldid' => '189','fldname' => 'SERBIA AND MONTENEGRO'),
            array('fldid' => '190','fldname' => 'SEYCHELLES'),
            array('fldid' => '191','fldname' => 'SIERRA LEONE'),
            array('fldid' => '192','fldname' => 'SINGAPORE'),
            array('fldid' => '193','fldname' => 'SLOVAKIA'),
            array('fldid' => '194','fldname' => 'SLOVENIA'),
            array('fldid' => '195','fldname' => 'SOLOMON ISLANDS'),
            array('fldid' => '196','fldname' => 'SOMALIA'),
            array('fldid' => '197','fldname' => 'SOUTH AFRICA'),
            array('fldid' => '198','fldname' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'),
            array('fldid' => '199','fldname' => 'SPAIN'),
            array('fldid' => '200','fldname' => 'SRI LANKA'),
            array('fldid' => '201','fldname' => 'SUDAN'),
            array('fldid' => '202','fldname' => 'SURINAME'),
            array('fldid' => '203','fldname' => 'SVALBARD AND JAN MAYEN'),
            array('fldid' => '204','fldname' => 'SWAZILAND'),
            array('fldid' => '205','fldname' => 'SWEDEN'),
            array('fldid' => '206','fldname' => 'SWITZERLAND'),
            array('fldid' => '207','fldname' => 'SYRIAN ARAB REPUBLIC'),
            array('fldid' => '208','fldname' => 'TAIWAN, PROVINCE OF CHINA'),
            array('fldid' => '209','fldname' => 'TAJIKISTAN'),
            array('fldid' => '210','fldname' => 'TANZANIA, UNITED REPUBLIC OF'),
            array('fldid' => '211','fldname' => 'THAILAND'),
            array('fldid' => '212','fldname' => 'TIMOR-LESTE'),
            array('fldid' => '213','fldname' => 'TOGO'),
            array('fldid' => '214','fldname' => 'TOKELAU'),
            array('fldid' => '215','fldname' => 'TONGA'),
            array('fldid' => '216','fldname' => 'TRINIDAD AND TOBAGO'),
            array('fldid' => '217','fldname' => 'TUNISIA'),
            array('fldid' => '218','fldname' => 'TURKEY'),
            array('fldid' => '219','fldname' => 'TURKMENISTAN'),
            array('fldid' => '220','fldname' => 'TURKS AND CAICOS ISLANDS'),
            array('fldid' => '221','fldname' => 'TUVALU'),
            array('fldid' => '222','fldname' => 'UGANDA'),
            array('fldid' => '223','fldname' => 'UKRAINE'),
            array('fldid' => '224','fldname' => 'UNITED ARAB EMIRATES'),
            array('fldid' => '225','fldname' => 'UNITED KINGDOM'),
            array('fldid' => '226','fldname' => 'UNITED STATES'),
            array('fldid' => '227','fldname' => 'UNITED STATES MINOR OUTLYING ISLANDS'),
            array('fldid' => '228','fldname' => 'URUGUAY'),
            array('fldid' => '229','fldname' => 'UZBEKISTAN'),
            array('fldid' => '230','fldname' => 'VANUATU'),
            array('fldid' => '231','fldname' => 'VENEZUELA'),
            array('fldid' => '232','fldname' => 'VIET NAM'),
            array('fldid' => '233','fldname' => 'VIRGIN ISLANDS, BRITISH'),
            array('fldid' => '234','fldname' => 'VIRGIN ISLANDS, U.S.'),
            array('fldid' => '235','fldname' => 'WALLIS AND FUTUNA'),
            array('fldid' => '236','fldname' => 'WESTERN SAHARA'),
            array('fldid' => '237','fldname' => 'YEMEN'),
            array('fldid' => '238','fldname' => 'ZAMBIA'),
            array('fldid' => '239','fldname' => 'ZIMBABWE'),
            array('fldid' => '240','fldname' => 'SERBIA'),
            array('fldid' => '241','fldname' => 'ASIA PACIFIC REGION'),
            array('fldid' => '242','fldname' => 'MONTENEGRO'),
            array('fldid' => '243','fldname' => 'ALAND ISLANDS'),
            array('fldid' => '244','fldname' => 'BONAIRE, SINT EUSTATIUS AND SABA'),
            array('fldid' => '245','fldname' => 'CURACAO'),
            array('fldid' => '246','fldname' => 'GUERNSEY'),
            array('fldid' => '247','fldname' => 'ISLE OF MAN'),
            array('fldid' => '248','fldname' => 'JERSEY'),
            array('fldid' => '249','fldname' => 'KOSOVO'),
            array('fldid' => '250','fldname' => 'SAINT BARTHELEMY'),
            array('fldid' => '251','fldname' => 'SAINT MARTIN'),
            array('fldid' => '252','fldname' => 'SINT MAARTEN'),
            array('fldid' => '253','fldname' => 'SOUTH SUDAN'),
          );

          DB::table('tblcountries')->insert($countries);

    }
}